// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: davans.proto

package kr.co.daontec.dto.proto;

public final class Davans {
  private Davans() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\014davans.proto\022\006davans\032\021davans.enum.prot" +
      "o\032\023davans.common.proto\032\025davans.m00.base." +
      "proto\032\030davans.m01.control.proto\032\026davans." +
      "m02.entry.proto\032\027davans.m03.search.proto" +
      "\032\025davans.m06.exit.proto\032\030davans.m07.regu" +
      "lar.proto\032\027davans.m08.listup.proto\032\032dava" +
      "ns.m09.broadcast.proto\032\030davans.m11.setti" +
      "ng.proto\032\027davans.m12.report.protoB\031\n\027kr." +
      "co.daontec.dto.protoP\000P\001P\002P\003P\004P\005P\006P\007P\010P\t" +
      "P\nP\013b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          kr.co.daontec.dto.proto.DavansEnum.getDescriptor(),
          kr.co.daontec.dto.proto.DavansCommon.getDescriptor(),
          kr.co.daontec.dto.proto.DavansM00Base.getDescriptor(),
          kr.co.daontec.dto.proto.DavansM01Control.getDescriptor(),
          kr.co.daontec.dto.proto.DavansM02Entry.getDescriptor(),
          kr.co.daontec.dto.proto.DavansM03Search.getDescriptor(),
          kr.co.daontec.dto.proto.DavansM06Exit.getDescriptor(),
          kr.co.daontec.dto.proto.DavansM07Regular.getDescriptor(),
          kr.co.daontec.dto.proto.DavansM08Listup.getDescriptor(),
          kr.co.daontec.dto.proto.DavansM09Broadcast.getDescriptor(),
          kr.co.daontec.dto.proto.DavansM11Setting.getDescriptor(),
          kr.co.daontec.dto.proto.DavansM12Report.getDescriptor(),
        });
    kr.co.daontec.dto.proto.DavansEnum.getDescriptor();
    kr.co.daontec.dto.proto.DavansCommon.getDescriptor();
    kr.co.daontec.dto.proto.DavansM00Base.getDescriptor();
    kr.co.daontec.dto.proto.DavansM01Control.getDescriptor();
    kr.co.daontec.dto.proto.DavansM02Entry.getDescriptor();
    kr.co.daontec.dto.proto.DavansM03Search.getDescriptor();
    kr.co.daontec.dto.proto.DavansM06Exit.getDescriptor();
    kr.co.daontec.dto.proto.DavansM07Regular.getDescriptor();
    kr.co.daontec.dto.proto.DavansM08Listup.getDescriptor();
    kr.co.daontec.dto.proto.DavansM09Broadcast.getDescriptor();
    kr.co.daontec.dto.proto.DavansM11Setting.getDescriptor();
    kr.co.daontec.dto.proto.DavansM12Report.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
