// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: davans.enum.proto

package kr.co.daontec.dto.proto;

public final class DavansEnum {
  private DavansEnum() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  /**
   * Protobuf enum {@code davans.message_type}
   */
  public enum message_type
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>M0000_DAVANS_ENUM = 0;</code>
     */
    M0000_DAVANS_ENUM(0),
    /**
     * <pre>
     * 초기화 요청
     * </pre>
     *
     * <code>M0001_DEVICE_INIT_REQ = 1;</code>
     */
    M0001_DEVICE_INIT_REQ(1),
    /**
     * <code>M0002_DEVICE_INIT_RES = 2;</code>
     */
    M0002_DEVICE_INIT_RES(2),
    /**
     * <pre>
     * 장비 상태정보
     * </pre>
     *
     * <code>M0003_DEVICE_STATUS_REQ = 3;</code>
     */
    M0003_DEVICE_STATUS_REQ(3),
    /**
     * <code>M0004_DEVICE_STATUS_RES = 4;</code>
     */
    M0004_DEVICE_STATUS_RES(4),
    /**
     * <pre>
     * 사용자 로그인
     * </pre>
     *
     * <code>M0005_USER_LOGIN_REQ = 5;</code>
     */
    M0005_USER_LOGIN_REQ(5),
    /**
     * <code>M0006_USER_LOGIN_RES = 6;</code>
     */
    M0006_USER_LOGIN_RES(6),
    /**
     * <pre>
     * 공통코드 리스트
     * </pre>
     *
     * <code>M0009_COMMON_CODE_LIST_REQ = 9;</code>
     */
    M0009_COMMON_CODE_LIST_REQ(9),
    /**
     * <code>M0010_COMMON_CODE_LIST_RES = 10;</code>
     */
    M0010_COMMON_CODE_LIST_RES(10),
    /**
     * <pre>
     * 장비 화면 위치 정보
     * </pre>
     *
     * <code>M0011_DEVICE_POSITION_INFO_REQ = 11;</code>
     */
    M0011_DEVICE_POSITION_INFO_REQ(11),
    /**
     * <code>M0012_DEVICE_POSITION_INFO_RES = 12;</code>
     */
    M0012_DEVICE_POSITION_INFO_RES(12),
    /**
     * <pre>
     * 장비 화면 위치 설정
     * </pre>
     *
     * <code>M0051_DEVICE_POSITION_SET_REQ = 51;</code>
     */
    M0051_DEVICE_POSITION_SET_REQ(51),
    /**
     * <code>M0052_DEVICE_POSITION_SET_RES = 52;</code>
     */
    M0052_DEVICE_POSITION_SET_RES(52),
    /**
     * <pre>
     * 비밀번호 변경
     * </pre>
     *
     * <code>M0061_CHANGE_PASSWORD_REQ = 61;</code>
     */
    M0061_CHANGE_PASSWORD_REQ(61),
    /**
     * <code>M0062_CHANGE_PASSWORD_RES = 62;</code>
     */
    M0062_CHANGE_PASSWORD_RES(62),
    /**
     * <pre>
     * 차단기 열림 통보
     * </pre>
     *
     * <code>M0101_GATE_OPENED_REQ = 101;</code>
     */
    M0101_GATE_OPENED_REQ(101),
    /**
     * <code>M0102_GATE_OPENED_RES = 102;</code>
     */
    M0102_GATE_OPENED_RES(102),
    /**
     * <pre>
     * 차단기 제어 요청
     * </pre>
     *
     * <code>M0103_GATE_CONTROL_USER_REQ = 103;</code>
     */
    M0103_GATE_CONTROL_USER_REQ(103),
    /**
     * <code>M0104_GATE_CONTROL_USER_RES = 104;</code>
     */
    M0104_GATE_CONTROL_USER_RES(104),
    /**
     * <code>M0105_GATE_CONTROL_DEVICE_REQ = 105;</code>
     */
    M0105_GATE_CONTROL_DEVICE_REQ(105),
    /**
     * <code>M0106_GATE_CONTROL_DEVICE_RES = 106;</code>
     */
    M0106_GATE_CONTROL_DEVICE_RES(106),
    /**
     * <pre>
     * 전광판 표시문구 변경 통보
     * </pre>
     *
     * <code>M0107_VMS_MSG_DEVICE_REQ = 107;</code>
     */
    M0107_VMS_MSG_DEVICE_REQ(107),
    /**
     * <code>M0108_VMS_MSG_DEVICE_RES = 108;</code>
     */
    M0108_VMS_MSG_DEVICE_RES(108),
    /**
     * <pre>
     * 원격 전원제어 요청
     * </pre>
     *
     * <code>M0111_POWER_CONTROL_USER_REQ = 111;</code>
     */
    M0111_POWER_CONTROL_USER_REQ(111),
    /**
     * <code>M0112_POWER_CONTROL_USER_RES = 112;</code>
     */
    M0112_POWER_CONTROL_USER_RES(112),
    /**
     * <code>M0113_POWER_CONTROL_DEVICE_REQ = 113;</code>
     */
    M0113_POWER_CONTROL_DEVICE_REQ(113),
    /**
     * <code>M0114_POWER_CONTROL_DEVICE_RES = 114;</code>
     */
    M0114_POWER_CONTROL_DEVICE_RES(114),
    /**
     * <code>M0121_GATE_CONTROL_SI_REQ = 121;</code>
     */
    M0121_GATE_CONTROL_SI_REQ(121),
    /**
     * <code>M0122_GATE_CONTROL_SI_RES = 122;</code>
     */
    M0122_GATE_CONTROL_SI_RES(122),
    /**
     * <pre>
     * 입차 요청
     * </pre>
     *
     * <code>M0201_CAR_ENTRY_REQ = 201;</code>
     */
    M0201_CAR_ENTRY_REQ(201),
    /**
     * <code>M0202_CAR_ENTRY_RES = 202;</code>
     */
    M0202_CAR_ENTRY_RES(202),
    /**
     * <pre>
     * 차량번호 변경
     * </pre>
     *
     * <code>M0205_CAR_REPLACE_REQ = 205;</code>
     */
    M0205_CAR_REPLACE_REQ(205),
    /**
     * <code>M0206_CAR_REPLACE_RES = 206;</code>
     */
    M0206_CAR_REPLACE_RES(206),
    /**
     * <pre>
     * 방문 입차 요청
     * </pre>
     *
     * <code>M0209_CAR_ENTRY_VISIT_REQ = 209;</code>
     */
    M0209_CAR_ENTRY_VISIT_REQ(209),
    /**
     * <code>M0210_CAR_ENTRY_VISIT_RES = 210;</code>
     */
    M0210_CAR_ENTRY_VISIT_RES(210),
    /**
     * <pre>
     * 자동 입차 설정/해제
     * </pre>
     *
     * <code>M0211_CAR_ENTRY_AUTOSET_REQ = 211;</code>
     */
    M0211_CAR_ENTRY_AUTOSET_REQ(211),
    /**
     * <code>M0212_CAR_ENTRY_AUTOSET_RES = 212;</code>
     */
    M0212_CAR_ENTRY_AUTOSET_RES(212),
    /**
     * <pre>
     * 세대알림(브로드캐스트 전송용)
     * </pre>
     *
     * <code>M0221_HOMENOTI_INFO_REQ = 221;</code>
     */
    M0221_HOMENOTI_INFO_REQ(221),
    /**
     * <code>M0221_HOMENOTI_INFO_RES = 222;</code>
     */
    M0221_HOMENOTI_INFO_RES(222),
    /**
     * <pre>
     * 입차증(방문증) 출력
     * </pre>
     *
     * <code>M0231_VISIT_RECEIPT_USER_REQ = 231;</code>
     */
    M0231_VISIT_RECEIPT_USER_REQ(231),
    /**
     * <code>M0232_VISIT_RECEIPT_USER_RES = 232;</code>
     */
    M0232_VISIT_RECEIPT_USER_RES(232),
    /**
     * <code>M0233_VISIT_RECEIPT_DEVICE_REQ = 233;</code>
     */
    M0233_VISIT_RECEIPT_DEVICE_REQ(233),
    /**
     * <code>M0234_VISIT_RECEIPT_DEVICE_RES = 234;</code>
     */
    M0234_VISIT_RECEIPT_DEVICE_RES(234),
    /**
     * <pre>
     * 직전 방문이력 조회
     * </pre>
     *
     * <code>M0235_VISIT_HISTORY_REQ = 235;</code>
     */
    M0235_VISIT_HISTORY_REQ(235),
    /**
     * <code>M0236_VISIT_HISTORY_RES = 236;</code>
     */
    M0236_VISIT_HISTORY_RES(236),
    /**
     * <pre>
     * 차량 정보 리스트
     * </pre>
     *
     * <code>M0301_CAR_INFO_LIST_REQ = 301;</code>
     */
    M0301_CAR_INFO_LIST_REQ(301),
    /**
     * <code>M0302_CAR_INFO_LIST_RES = 302;</code>
     */
    M0302_CAR_INFO_LIST_RES(302),
    /**
     * <pre>
     * 차량 리스트
     * </pre>
     *
     * <code>M0303_CAR_LIST_REQ = 303;</code>
     */
    M0303_CAR_LIST_REQ(303),
    /**
     * <code>M0304_CAR_LIST_RES = 304;</code>
     */
    M0304_CAR_LIST_RES(304),
    /**
     * <pre>
     * 주차가능 대수 조회
     * </pre>
     *
     * <code>M0313_PARKABLE_CNT_REQ = 313;</code>
     */
    M0313_PARKABLE_CNT_REQ(313),
    /**
     * <code>M0314_PARKABLE_CNT_RES = 314;</code>
     */
    M0314_PARKABLE_CNT_RES(314),
    /**
     * <pre>
     * 사용가능 등록차량 리스트
     * </pre>
     *
     * <code>M0321_USABLE_REGIST_LIST_REQ = 321;</code>
     */
    M0321_USABLE_REGIST_LIST_REQ(321),
    /**
     * <code>M0322_USABLE_REGIST_LIST_RES = 322;</code>
     */
    M0322_USABLE_REGIST_LIST_RES(322),
    /**
     * <pre>
     * 미처리 차량 리스트
     * </pre>
     *
     * <code>M0331_CAR_UNPROCESSED_LIST_REQ = 331;</code>
     */
    M0331_CAR_UNPROCESSED_LIST_REQ(331),
    /**
     * <code>M0332_CAR_UNPROCESSED_LIST_RES = 332;</code>
     */
    M0332_CAR_UNPROCESSED_LIST_RES(332),
    /**
     * <pre>
     * 수동 출차
     * </pre>
     *
     * <code>M0601_CAR_OUT_MANUAL_REQ = 601;</code>
     */
    M0601_CAR_OUT_MANUAL_REQ(601),
    /**
     * <code>M0602_CAR_OUT_MANUAL_RES = 602;</code>
     */
    M0602_CAR_OUT_MANUAL_RES(602),
    /**
     * <pre>
     * 출차 요청
     * </pre>
     *
     * <code>M0603_CAR_EXIT_REQ = 603;</code>
     */
    M0603_CAR_EXIT_REQ(603),
    /**
     * <code>M0604_CAR_EXIT_RES = 604;</code>
     */
    M0604_CAR_EXIT_RES(604),
    /**
     * <pre>
     * 등록차량 조회
     * </pre>
     *
     * <code>M0701_RGST_INFO_LIST_REQ = 701;</code>
     */
    M0701_RGST_INFO_LIST_REQ(701),
    /**
     * <code>M0702_RGST_INFO_LIST_RES = 702;</code>
     */
    M0702_RGST_INFO_LIST_RES(702),
    /**
     * <pre>
     * 등록차량 등록
     * </pre>
     *
     * <code>M0707_RGST_REG_COMMIT_REQ = 707;</code>
     */
    M0707_RGST_REG_COMMIT_REQ(707),
    /**
     * <code>M0708_RGST_REG_COMMIT_RES = 708;</code>
     */
    M0708_RGST_REG_COMMIT_RES(708),
    /**
     * <pre>
     * 등록차량 이력
     * </pre>
     *
     * <code>M0711_RGST_REG_RECORD_REQ = 711;</code>
     */
    M0711_RGST_REG_RECORD_REQ(711),
    /**
     * <code>M0712_RGST_REG_RECORD_RES = 712;</code>
     */
    M0712_RGST_REG_RECORD_RES(712),
    /**
     * <pre>
     * 방문 예약 관리(조회)
     * </pre>
     *
     * <code>M0721_VISIT_RESERVE_SEARCH_REQ = 721;</code>
     */
    M0721_VISIT_RESERVE_SEARCH_REQ(721),
    /**
     * <code>M0722_VISIT_RESERVE_SEARCH_RES = 722;</code>
     */
    M0722_VISIT_RESERVE_SEARCH_RES(722),
    /**
     * <pre>
     * 방문 예약 관리(설정)
     * </pre>
     *
     * <code>M0723_VISIT_RESERVE_REGIST_REQ = 723;</code>
     */
    M0723_VISIT_RESERVE_REGIST_REQ(723),
    /**
     * <code>M0724_VISIT_RESERVE_REGIST_RES = 724;</code>
     */
    M0724_VISIT_RESERVE_REGIST_RES(724),
    /**
     * <pre>
     * 방문 예약 이력
     * </pre>
     *
     * <code>M0725_VISIT_RESERVE_RECORD_REQ = 725;</code>
     */
    M0725_VISIT_RESERVE_RECORD_REQ(725),
    /**
     * <code>M0726_VISIT_RESERVE_RECORD_RES = 726;</code>
     */
    M0726_VISIT_RESERVE_RECORD_RES(726),
    /**
     * <pre>
     * RF 태그 리스트
     * </pre>
     *
     * <code>M0731_RGST_RF_LIST_REQ = 731;</code>
     */
    M0731_RGST_RF_LIST_REQ(731),
    /**
     * <code>M0732_RGST_RF_LIST_RES = 732;</code>
     */
    M0732_RGST_RF_LIST_RES(732),
    /**
     * <pre>
     * RF 태그 등록
     * </pre>
     *
     * <code>M0733_RGST_RF_COMMIT_REQ = 733;</code>
     */
    M0733_RGST_RF_COMMIT_REQ(733),
    /**
     * <code>M0734_RGST_RF_COMMIT_RES = 734;</code>
     */
    M0734_RGST_RF_COMMIT_RES(734),
    /**
     * <pre>
     * 공무(공용)차량 관리(조회)
     * </pre>
     *
     * <code>M0741_OFFICIAL_SEARCH_REQ = 741;</code>
     */
    M0741_OFFICIAL_SEARCH_REQ(741),
    /**
     * <code>M0742_OFFICIAL_SEARCH_RES = 742;</code>
     */
    M0742_OFFICIAL_SEARCH_RES(742),
    /**
     * <pre>
     * 공무(공용)차량 관리(설정)
     * </pre>
     *
     * <code>M0743_OFFICIAL_REGIST_REQ = 743;</code>
     */
    M0743_OFFICIAL_REGIST_REQ(743),
    /**
     * <code>M0744_OFFICIAL_REGIST_RES = 744;</code>
     */
    M0744_OFFICIAL_REGIST_RES(744),
    /**
     * <pre>
     * 주차장명 리스트업
     * </pre>
     *
     * <code>M0801_LISTUP_PARK_REQ = 801;</code>
     */
    M0801_LISTUP_PARK_REQ(801),
    /**
     * <code>M0802_LISTUP_PARK_RES = 802;</code>
     */
    M0802_LISTUP_PARK_RES(802),
    /**
     * <pre>
     * 구역명 리스트업
     * </pre>
     *
     * <code>M0803_LISTUP_ZONE_REQ = 803;</code>
     */
    M0803_LISTUP_ZONE_REQ(803),
    /**
     * <code>M0804_LISTUP_ZONE_RES = 804;</code>
     */
    M0804_LISTUP_ZONE_RES(804),
    /**
     * <pre>
     * b_장비 상태 정보
     * </pre>
     *
     * <code>M0901_B_DEVICE_INFO = 901;</code>
     */
    M0901_B_DEVICE_INFO(901),
    /**
     * <pre>
     * b_입차 요청
     * </pre>
     *
     * <code>M0902_B_CAR_ENTRY_REQ = 902;</code>
     */
    M0902_B_CAR_ENTRY_REQ(902),
    /**
     * <pre>
     * b_입차 완료
     * </pre>
     *
     * <code>M0903_B_CAR_ENTRY_COMPLATE = 903;</code>
     */
    M0903_B_CAR_ENTRY_COMPLATE(903),
    /**
     * <pre>
     * b_출차 요청
     * </pre>
     *
     * <code>M0905_B_CAR_EXIT_REQ = 905;</code>
     */
    M0905_B_CAR_EXIT_REQ(905),
    /**
     * <pre>
     * b_출차 완료
     * </pre>
     *
     * <code>M0906_B_CAR_EXIT_COMPLATE = 906;</code>
     */
    M0906_B_CAR_EXIT_COMPLATE(906),
    /**
     * <pre>
     * b_알림 차량
     * </pre>
     *
     * <code>M0908_B_ALARM_INFO = 908;</code>
     */
    M0908_B_ALARM_INFO(908),
    /**
     * <pre>
     * b_주차가능 대수
     * </pre>
     *
     * <code>M0909_B_PARKABLE_CNT = 909;</code>
     */
    M0909_B_PARKABLE_CNT(909),
    /**
     * <pre>
     * b_세대알림 통보
     * </pre>
     *
     * <code>M0910_B_HOMENOTI_INFO = 910;</code>
     */
    M0910_B_HOMENOTI_INFO(910),
    /**
     * <pre>
     * b_세대통보 요청(홈넷 중계서버에서 받아서 처리할 데이터 전송)
     * </pre>
     *
     * <code>M0911_B_HOMENOTI_REQ = 911;</code>
     */
    M0911_B_HOMENOTI_REQ(911),
    /**
     * <pre>
     * b_입차 데이터 보정(보조 카메라로 찍어서 차량번호 보정할 경우)
     * </pre>
     *
     * <code>M0912_B_CAR_REPLACE = 912;</code>
     */
    M0912_B_CAR_REPLACE(912),
    /**
     * <pre>
     * 사용자 관리(조회)
     * </pre>
     *
     * <code>M1101_USERSET_SEARCH_REQ = 1101;</code>
     */
    M1101_USERSET_SEARCH_REQ(1101),
    /**
     * <code>M1102_USERSET_SEARCH_RES = 1102;</code>
     */
    M1102_USERSET_SEARCH_RES(1102),
    /**
     * <pre>
     * 사용자 관리(설정)
     * </pre>
     *
     * <code>M1103_USERSET_REGIST_REQ = 1103;</code>
     */
    M1103_USERSET_REGIST_REQ(1103),
    /**
     * <code>M1104_USERSET_REGIST_RES = 1104;</code>
     */
    M1104_USERSET_REGIST_RES(1104),
    /**
     * <pre>
     * 주차장 관리(조회)
     * </pre>
     *
     * <code>M1105_PARKSET_SEARCH_REQ = 1105;</code>
     */
    M1105_PARKSET_SEARCH_REQ(1105),
    /**
     * <code>M1106_PARKSET_SEARCH_RES = 1106;</code>
     */
    M1106_PARKSET_SEARCH_RES(1106),
    /**
     * <pre>
     * 주차장 관리(설정)
     * </pre>
     *
     * <code>M1107_PARKSET_REGIST_REQ = 1107;</code>
     */
    M1107_PARKSET_REGIST_REQ(1107),
    /**
     * <code>M1108_PARKSET_REGIST_RES = 1108;</code>
     */
    M1108_PARKSET_REGIST_RES(1108),
    /**
     * <pre>
     * 주차 구역 관리(조회)
     * </pre>
     *
     * <code>M1109_ZONESET_SEARCH_REQ = 1109;</code>
     */
    M1109_ZONESET_SEARCH_REQ(1109),
    /**
     * <code>M1110_ZONESET_SEARCH_RES = 1110;</code>
     */
    M1110_ZONESET_SEARCH_RES(1110),
    /**
     * <pre>
     * 주차 구역 관리(설정)
     * </pre>
     *
     * <code>M1111_ZONESET_REGIST_REQ = 1111;</code>
     */
    M1111_ZONESET_REGIST_REQ(1111),
    /**
     * <code>M1112_ZONESET_REGIST_RES = 1112;</code>
     */
    M1112_ZONESET_REGIST_RES(1112),
    /**
     * <pre>
     * 장비 관리(조회)
     * </pre>
     *
     * <code>M1113_DEVICESET_SEARCH_REQ = 1113;</code>
     */
    M1113_DEVICESET_SEARCH_REQ(1113),
    /**
     * <code>M1114_DEVICESET_SEARCH_RES = 1114;</code>
     */
    M1114_DEVICESET_SEARCH_RES(1114),
    /**
     * <pre>
     * 장비 관리(설정)
     * </pre>
     *
     * <code>M1115_DEVICESET_REGIST_REQ = 1115;</code>
     */
    M1115_DEVICESET_REGIST_REQ(1115),
    /**
     * <code>M1116_DEVICESET_REGIST_RES = 1116;</code>
     */
    M1116_DEVICESET_REGIST_RES(1116),
    /**
     * <pre>
     * 코드 관리(조회)
     * </pre>
     *
     * <code>M1117_CODESET_SEARCH_REQ = 1117;</code>
     */
    M1117_CODESET_SEARCH_REQ(1117),
    /**
     * <code>M1118_CODESET_SEARCH_RES = 1118;</code>
     */
    M1118_CODESET_SEARCH_RES(1118),
    /**
     * <pre>
     * 코드 관리(설정)
     * </pre>
     *
     * <code>M1119_CODESET_REGIST_REQ = 1119;</code>
     */
    M1119_CODESET_REGIST_REQ(1119),
    /**
     * <code>M1120_CODESET_REGIST_RES = 1120;</code>
     */
    M1120_CODESET_REGIST_RES(1120),
    /**
     * <pre>
     * 패턴 번호 관리(조회)
     * </pre>
     *
     * <code>M1121_PATTERN_SEARCH_REQ = 1121;</code>
     */
    M1121_PATTERN_SEARCH_REQ(1121),
    /**
     * <code>M1122_PATTERN_SEARCH_RES = 1122;</code>
     */
    M1122_PATTERN_SEARCH_RES(1122),
    /**
     * <pre>
     * 패턴 번호 관리(설정)
     * </pre>
     *
     * <code>M1123_PATTERN_REGIST_REQ = 1123;</code>
     */
    M1123_PATTERN_REGIST_REQ(1123),
    /**
     * <code>M1124_PATTERN_REGIST_RES = 1124;</code>
     */
    M1124_PATTERN_REGIST_RES(1124),
    /**
     * <pre>
     * 전원제어기 관리(조회)
     * </pre>
     *
     * <code>M1131_POWER_CONTROLLER_LIST_REQ = 1131;</code>
     */
    M1131_POWER_CONTROLLER_LIST_REQ(1131),
    /**
     * <code>M1132_POWER_CONTROLLER_LIST_RES = 1132;</code>
     */
    M1132_POWER_CONTROLLER_LIST_RES(1132),
    /**
     * <pre>
     * 전원제어기 관리(설정)
     * </pre>
     *
     * <code>M1133_POWER_CONTROLLER_SET_REQ = 1133;</code>
     */
    M1133_POWER_CONTROLLER_SET_REQ(1133),
    /**
     * <code>M1134_POWER_CONTROLLER_SET_RES = 1134;</code>
     */
    M1134_POWER_CONTROLLER_SET_RES(1134),
    /**
     * <pre>
     * 단독 전광판 관리(조회)
     * </pre>
     *
     * <code>M1141_VMSSET_SEARCH_REQ = 1141;</code>
     */
    M1141_VMSSET_SEARCH_REQ(1141),
    /**
     * <code>M1142_VMSSET_SEARCH_RES = 1142;</code>
     */
    M1142_VMSSET_SEARCH_RES(1142),
    /**
     * <pre>
     * 단독 전광판 관리(설정)
     * </pre>
     *
     * <code>M1143_VMSSET_REGIST_REQ = 1143;</code>
     */
    M1143_VMSSET_REGIST_REQ(1143),
    /**
     * <code>M1144_VMSSET_REGIST_RES = 1144;</code>
     */
    M1144_VMSSET_REGIST_RES(1144),
    /**
     * <pre>
     * 블랙리스트 관리(조회)
     * </pre>
     *
     * <code>M1151_BLACKLISTSET_SEARCH_REQ = 1151;</code>
     */
    M1151_BLACKLISTSET_SEARCH_REQ(1151),
    /**
     * <code>M1152_BLACKLISTSET_SEARCH_RES = 1152;</code>
     */
    M1152_BLACKLISTSET_SEARCH_RES(1152),
    /**
     * <pre>
     * 블랙리스트 관리(설정)
     * </pre>
     *
     * <code>M1153_BLACKLISTSET_REGIST_REQ = 1153;</code>
     */
    M1153_BLACKLISTSET_REGIST_REQ(1153),
    /**
     * <code>M1154_BLACKLISTSET_REGIST_RES = 1154;</code>
     */
    M1154_BLACKLISTSET_REGIST_RES(1154),
    /**
     * <pre>
     * 휴일 관리(조회)
     * </pre>
     *
     * <code>M1161_HOLIDAYSET_SEARCH_REQ = 1161;</code>
     */
    M1161_HOLIDAYSET_SEARCH_REQ(1161),
    /**
     * <code>M1162_HOLIDAYSET_SEARCH_RES = 1162;</code>
     */
    M1162_HOLIDAYSET_SEARCH_RES(1162),
    /**
     * <pre>
     * 휴일 관리(설정)
     * </pre>
     *
     * <code>M1163_HOLIDAYSET_REGIST_REQ = 1163;</code>
     */
    M1163_HOLIDAYSET_REGIST_REQ(1163),
    /**
     * <code>M1164_HOLIDAYSET_REGIST_RES = 1164;</code>
     */
    M1164_HOLIDAYSET_REGIST_RES(1164),
    /**
     * <pre>
     * 유도전광판(입구만차전광판) 관리(조회)
     * </pre>
     *
     * <code>M1171_GUIDANCEVMSSET_SEARCH_REQ = 1171;</code>
     */
    M1171_GUIDANCEVMSSET_SEARCH_REQ(1171),
    /**
     * <code>M1172_GUIDANCEVMSSET_SEARCH_RES = 1172;</code>
     */
    M1172_GUIDANCEVMSSET_SEARCH_RES(1172),
    /**
     * <pre>
     * 유도전광판(입구만차전광판) 관리(설정)
     * </pre>
     *
     * <code>M1173_GUIDANCEVMSSET_REGIST_REQ = 1173;</code>
     */
    M1173_GUIDANCEVMSSET_REGIST_REQ(1173),
    /**
     * <code>M1174_GUIDANCEVMSSET_REGIST_RES = 1174;</code>
     */
    M1174_GUIDANCEVMSSET_REGIST_RES(1174),
    /**
     * <pre>
     * 스케줄러 관리(조회)
     * </pre>
     *
     * <code>M1175_SCHEDULERSET_SEARCH_REQ = 1175;</code>
     */
    M1175_SCHEDULERSET_SEARCH_REQ(1175),
    /**
     * <code>M1176_SCHEDULERSET_SEARCH_RES = 1176;</code>
     */
    M1176_SCHEDULERSET_SEARCH_RES(1176),
    /**
     * <pre>
     * 스케줄러 관리(설정)
     * </pre>
     *
     * <code>M1177_SCHEDULERSET_REGIST_REQ = 1177;</code>
     */
    M1177_SCHEDULERSET_REGIST_REQ(1177),
    /**
     * <code>M1178_SCHEDULERSET_REGIST_RES = 1178;</code>
     */
    M1178_SCHEDULERSET_REGIST_RES(1178),
    /**
     * <pre>
     * DB초기화
     * </pre>
     *
     * <code>M1181_DB_CLEAR_REQ = 1181;</code>
     */
    M1181_DB_CLEAR_REQ(1181),
    /**
     * <code>M1182_DB_CLEAR_RES = 1182;</code>
     */
    M1182_DB_CLEAR_RES(1182),
    /**
     * <pre>
     * 기간별 입차현황
     * </pre>
     *
     * <code>M1201_ENTRY_LIST_TERM_REQ = 1201;</code>
     */
    M1201_ENTRY_LIST_TERM_REQ(1201),
    /**
     * <code>M1202_ENTRY_LIST_TERM_RES = 1202;</code>
     */
    M1202_ENTRY_LIST_TERM_RES(1202),
    /**
     * <pre>
     * 정기권 현황
     * </pre>
     *
     * <code>M1203_REGULAR_LIST_REQ = 1203;</code>
     */
    M1203_REGULAR_LIST_REQ(1203),
    /**
     * <code>M1204_REGULAR_LIST_RES = 1204;</code>
     */
    M1204_REGULAR_LIST_RES(1204),
    /**
     * <pre>
     * 방문자 현황
     * </pre>
     *
     * <code>M1205_VISIT_RESERVE_LIST_REQ = 1205;</code>
     */
    M1205_VISIT_RESERVE_LIST_REQ(1205),
    /**
     * <code>M1206_VISIT_RESERVE_LIST_RES = 1206;</code>
     */
    M1206_VISIT_RESERVE_LIST_RES(1206),
    /**
     * <pre>
     * 방문차량 집계
     * </pre>
     *
     * <code>M1207_VISIT_LIST_TOTAL_REQ = 1207;</code>
     */
    M1207_VISIT_LIST_TOTAL_REQ(1207),
    /**
     * <code>M1208_VISIT_LIST_TOTAL_RES = 1208;</code>
     */
    M1208_VISIT_LIST_TOTAL_RES(1208),
    /**
     * <pre>
     * 기간별 입차 횟수
     * </pre>
     *
     * <code>M1209_ENTRY_COUNT_TERM_REQ = 1209;</code>
     */
    M1209_ENTRY_COUNT_TERM_REQ(1209),
    /**
     * <code>M1210_ENTRY_COUNT_TERM_RES = 1210;</code>
     */
    M1210_ENTRY_COUNT_TERM_RES(1210),
    UNRECOGNIZED(-1),
    ;

    /**
     * <code>M0000_DAVANS_ENUM = 0;</code>
     */
    public static final int M0000_DAVANS_ENUM_VALUE = 0;
    /**
     * <pre>
     * 초기화 요청
     * </pre>
     *
     * <code>M0001_DEVICE_INIT_REQ = 1;</code>
     */
    public static final int M0001_DEVICE_INIT_REQ_VALUE = 1;
    /**
     * <code>M0002_DEVICE_INIT_RES = 2;</code>
     */
    public static final int M0002_DEVICE_INIT_RES_VALUE = 2;
    /**
     * <pre>
     * 장비 상태정보
     * </pre>
     *
     * <code>M0003_DEVICE_STATUS_REQ = 3;</code>
     */
    public static final int M0003_DEVICE_STATUS_REQ_VALUE = 3;
    /**
     * <code>M0004_DEVICE_STATUS_RES = 4;</code>
     */
    public static final int M0004_DEVICE_STATUS_RES_VALUE = 4;
    /**
     * <pre>
     * 사용자 로그인
     * </pre>
     *
     * <code>M0005_USER_LOGIN_REQ = 5;</code>
     */
    public static final int M0005_USER_LOGIN_REQ_VALUE = 5;
    /**
     * <code>M0006_USER_LOGIN_RES = 6;</code>
     */
    public static final int M0006_USER_LOGIN_RES_VALUE = 6;
    /**
     * <pre>
     * 공통코드 리스트
     * </pre>
     *
     * <code>M0009_COMMON_CODE_LIST_REQ = 9;</code>
     */
    public static final int M0009_COMMON_CODE_LIST_REQ_VALUE = 9;
    /**
     * <code>M0010_COMMON_CODE_LIST_RES = 10;</code>
     */
    public static final int M0010_COMMON_CODE_LIST_RES_VALUE = 10;
    /**
     * <pre>
     * 장비 화면 위치 정보
     * </pre>
     *
     * <code>M0011_DEVICE_POSITION_INFO_REQ = 11;</code>
     */
    public static final int M0011_DEVICE_POSITION_INFO_REQ_VALUE = 11;
    /**
     * <code>M0012_DEVICE_POSITION_INFO_RES = 12;</code>
     */
    public static final int M0012_DEVICE_POSITION_INFO_RES_VALUE = 12;
    /**
     * <pre>
     * 장비 화면 위치 설정
     * </pre>
     *
     * <code>M0051_DEVICE_POSITION_SET_REQ = 51;</code>
     */
    public static final int M0051_DEVICE_POSITION_SET_REQ_VALUE = 51;
    /**
     * <code>M0052_DEVICE_POSITION_SET_RES = 52;</code>
     */
    public static final int M0052_DEVICE_POSITION_SET_RES_VALUE = 52;
    /**
     * <pre>
     * 비밀번호 변경
     * </pre>
     *
     * <code>M0061_CHANGE_PASSWORD_REQ = 61;</code>
     */
    public static final int M0061_CHANGE_PASSWORD_REQ_VALUE = 61;
    /**
     * <code>M0062_CHANGE_PASSWORD_RES = 62;</code>
     */
    public static final int M0062_CHANGE_PASSWORD_RES_VALUE = 62;
    /**
     * <pre>
     * 차단기 열림 통보
     * </pre>
     *
     * <code>M0101_GATE_OPENED_REQ = 101;</code>
     */
    public static final int M0101_GATE_OPENED_REQ_VALUE = 101;
    /**
     * <code>M0102_GATE_OPENED_RES = 102;</code>
     */
    public static final int M0102_GATE_OPENED_RES_VALUE = 102;
    /**
     * <pre>
     * 차단기 제어 요청
     * </pre>
     *
     * <code>M0103_GATE_CONTROL_USER_REQ = 103;</code>
     */
    public static final int M0103_GATE_CONTROL_USER_REQ_VALUE = 103;
    /**
     * <code>M0104_GATE_CONTROL_USER_RES = 104;</code>
     */
    public static final int M0104_GATE_CONTROL_USER_RES_VALUE = 104;
    /**
     * <code>M0105_GATE_CONTROL_DEVICE_REQ = 105;</code>
     */
    public static final int M0105_GATE_CONTROL_DEVICE_REQ_VALUE = 105;
    /**
     * <code>M0106_GATE_CONTROL_DEVICE_RES = 106;</code>
     */
    public static final int M0106_GATE_CONTROL_DEVICE_RES_VALUE = 106;
    /**
     * <pre>
     * 전광판 표시문구 변경 통보
     * </pre>
     *
     * <code>M0107_VMS_MSG_DEVICE_REQ = 107;</code>
     */
    public static final int M0107_VMS_MSG_DEVICE_REQ_VALUE = 107;
    /**
     * <code>M0108_VMS_MSG_DEVICE_RES = 108;</code>
     */
    public static final int M0108_VMS_MSG_DEVICE_RES_VALUE = 108;
    /**
     * <pre>
     * 원격 전원제어 요청
     * </pre>
     *
     * <code>M0111_POWER_CONTROL_USER_REQ = 111;</code>
     */
    public static final int M0111_POWER_CONTROL_USER_REQ_VALUE = 111;
    /**
     * <code>M0112_POWER_CONTROL_USER_RES = 112;</code>
     */
    public static final int M0112_POWER_CONTROL_USER_RES_VALUE = 112;
    /**
     * <code>M0113_POWER_CONTROL_DEVICE_REQ = 113;</code>
     */
    public static final int M0113_POWER_CONTROL_DEVICE_REQ_VALUE = 113;
    /**
     * <code>M0114_POWER_CONTROL_DEVICE_RES = 114;</code>
     */
    public static final int M0114_POWER_CONTROL_DEVICE_RES_VALUE = 114;
    /**
     * <code>M0121_GATE_CONTROL_SI_REQ = 121;</code>
     */
    public static final int M0121_GATE_CONTROL_SI_REQ_VALUE = 121;
    /**
     * <code>M0122_GATE_CONTROL_SI_RES = 122;</code>
     */
    public static final int M0122_GATE_CONTROL_SI_RES_VALUE = 122;
    /**
     * <pre>
     * 입차 요청
     * </pre>
     *
     * <code>M0201_CAR_ENTRY_REQ = 201;</code>
     */
    public static final int M0201_CAR_ENTRY_REQ_VALUE = 201;
    /**
     * <code>M0202_CAR_ENTRY_RES = 202;</code>
     */
    public static final int M0202_CAR_ENTRY_RES_VALUE = 202;
    /**
     * <pre>
     * 차량번호 변경
     * </pre>
     *
     * <code>M0205_CAR_REPLACE_REQ = 205;</code>
     */
    public static final int M0205_CAR_REPLACE_REQ_VALUE = 205;
    /**
     * <code>M0206_CAR_REPLACE_RES = 206;</code>
     */
    public static final int M0206_CAR_REPLACE_RES_VALUE = 206;
    /**
     * <pre>
     * 방문 입차 요청
     * </pre>
     *
     * <code>M0209_CAR_ENTRY_VISIT_REQ = 209;</code>
     */
    public static final int M0209_CAR_ENTRY_VISIT_REQ_VALUE = 209;
    /**
     * <code>M0210_CAR_ENTRY_VISIT_RES = 210;</code>
     */
    public static final int M0210_CAR_ENTRY_VISIT_RES_VALUE = 210;
    /**
     * <pre>
     * 자동 입차 설정/해제
     * </pre>
     *
     * <code>M0211_CAR_ENTRY_AUTOSET_REQ = 211;</code>
     */
    public static final int M0211_CAR_ENTRY_AUTOSET_REQ_VALUE = 211;
    /**
     * <code>M0212_CAR_ENTRY_AUTOSET_RES = 212;</code>
     */
    public static final int M0212_CAR_ENTRY_AUTOSET_RES_VALUE = 212;
    /**
     * <pre>
     * 세대알림(브로드캐스트 전송용)
     * </pre>
     *
     * <code>M0221_HOMENOTI_INFO_REQ = 221;</code>
     */
    public static final int M0221_HOMENOTI_INFO_REQ_VALUE = 221;
    /**
     * <code>M0221_HOMENOTI_INFO_RES = 222;</code>
     */
    public static final int M0221_HOMENOTI_INFO_RES_VALUE = 222;
    /**
     * <pre>
     * 입차증(방문증) 출력
     * </pre>
     *
     * <code>M0231_VISIT_RECEIPT_USER_REQ = 231;</code>
     */
    public static final int M0231_VISIT_RECEIPT_USER_REQ_VALUE = 231;
    /**
     * <code>M0232_VISIT_RECEIPT_USER_RES = 232;</code>
     */
    public static final int M0232_VISIT_RECEIPT_USER_RES_VALUE = 232;
    /**
     * <code>M0233_VISIT_RECEIPT_DEVICE_REQ = 233;</code>
     */
    public static final int M0233_VISIT_RECEIPT_DEVICE_REQ_VALUE = 233;
    /**
     * <code>M0234_VISIT_RECEIPT_DEVICE_RES = 234;</code>
     */
    public static final int M0234_VISIT_RECEIPT_DEVICE_RES_VALUE = 234;
    /**
     * <pre>
     * 직전 방문이력 조회
     * </pre>
     *
     * <code>M0235_VISIT_HISTORY_REQ = 235;</code>
     */
    public static final int M0235_VISIT_HISTORY_REQ_VALUE = 235;
    /**
     * <code>M0236_VISIT_HISTORY_RES = 236;</code>
     */
    public static final int M0236_VISIT_HISTORY_RES_VALUE = 236;
    /**
     * <pre>
     * 차량 정보 리스트
     * </pre>
     *
     * <code>M0301_CAR_INFO_LIST_REQ = 301;</code>
     */
    public static final int M0301_CAR_INFO_LIST_REQ_VALUE = 301;
    /**
     * <code>M0302_CAR_INFO_LIST_RES = 302;</code>
     */
    public static final int M0302_CAR_INFO_LIST_RES_VALUE = 302;
    /**
     * <pre>
     * 차량 리스트
     * </pre>
     *
     * <code>M0303_CAR_LIST_REQ = 303;</code>
     */
    public static final int M0303_CAR_LIST_REQ_VALUE = 303;
    /**
     * <code>M0304_CAR_LIST_RES = 304;</code>
     */
    public static final int M0304_CAR_LIST_RES_VALUE = 304;
    /**
     * <pre>
     * 주차가능 대수 조회
     * </pre>
     *
     * <code>M0313_PARKABLE_CNT_REQ = 313;</code>
     */
    public static final int M0313_PARKABLE_CNT_REQ_VALUE = 313;
    /**
     * <code>M0314_PARKABLE_CNT_RES = 314;</code>
     */
    public static final int M0314_PARKABLE_CNT_RES_VALUE = 314;
    /**
     * <pre>
     * 사용가능 등록차량 리스트
     * </pre>
     *
     * <code>M0321_USABLE_REGIST_LIST_REQ = 321;</code>
     */
    public static final int M0321_USABLE_REGIST_LIST_REQ_VALUE = 321;
    /**
     * <code>M0322_USABLE_REGIST_LIST_RES = 322;</code>
     */
    public static final int M0322_USABLE_REGIST_LIST_RES_VALUE = 322;
    /**
     * <pre>
     * 미처리 차량 리스트
     * </pre>
     *
     * <code>M0331_CAR_UNPROCESSED_LIST_REQ = 331;</code>
     */
    public static final int M0331_CAR_UNPROCESSED_LIST_REQ_VALUE = 331;
    /**
     * <code>M0332_CAR_UNPROCESSED_LIST_RES = 332;</code>
     */
    public static final int M0332_CAR_UNPROCESSED_LIST_RES_VALUE = 332;
    /**
     * <pre>
     * 수동 출차
     * </pre>
     *
     * <code>M0601_CAR_OUT_MANUAL_REQ = 601;</code>
     */
    public static final int M0601_CAR_OUT_MANUAL_REQ_VALUE = 601;
    /**
     * <code>M0602_CAR_OUT_MANUAL_RES = 602;</code>
     */
    public static final int M0602_CAR_OUT_MANUAL_RES_VALUE = 602;
    /**
     * <pre>
     * 출차 요청
     * </pre>
     *
     * <code>M0603_CAR_EXIT_REQ = 603;</code>
     */
    public static final int M0603_CAR_EXIT_REQ_VALUE = 603;
    /**
     * <code>M0604_CAR_EXIT_RES = 604;</code>
     */
    public static final int M0604_CAR_EXIT_RES_VALUE = 604;
    /**
     * <pre>
     * 등록차량 조회
     * </pre>
     *
     * <code>M0701_RGST_INFO_LIST_REQ = 701;</code>
     */
    public static final int M0701_RGST_INFO_LIST_REQ_VALUE = 701;
    /**
     * <code>M0702_RGST_INFO_LIST_RES = 702;</code>
     */
    public static final int M0702_RGST_INFO_LIST_RES_VALUE = 702;
    /**
     * <pre>
     * 등록차량 등록
     * </pre>
     *
     * <code>M0707_RGST_REG_COMMIT_REQ = 707;</code>
     */
    public static final int M0707_RGST_REG_COMMIT_REQ_VALUE = 707;
    /**
     * <code>M0708_RGST_REG_COMMIT_RES = 708;</code>
     */
    public static final int M0708_RGST_REG_COMMIT_RES_VALUE = 708;
    /**
     * <pre>
     * 등록차량 이력
     * </pre>
     *
     * <code>M0711_RGST_REG_RECORD_REQ = 711;</code>
     */
    public static final int M0711_RGST_REG_RECORD_REQ_VALUE = 711;
    /**
     * <code>M0712_RGST_REG_RECORD_RES = 712;</code>
     */
    public static final int M0712_RGST_REG_RECORD_RES_VALUE = 712;
    /**
     * <pre>
     * 방문 예약 관리(조회)
     * </pre>
     *
     * <code>M0721_VISIT_RESERVE_SEARCH_REQ = 721;</code>
     */
    public static final int M0721_VISIT_RESERVE_SEARCH_REQ_VALUE = 721;
    /**
     * <code>M0722_VISIT_RESERVE_SEARCH_RES = 722;</code>
     */
    public static final int M0722_VISIT_RESERVE_SEARCH_RES_VALUE = 722;
    /**
     * <pre>
     * 방문 예약 관리(설정)
     * </pre>
     *
     * <code>M0723_VISIT_RESERVE_REGIST_REQ = 723;</code>
     */
    public static final int M0723_VISIT_RESERVE_REGIST_REQ_VALUE = 723;
    /**
     * <code>M0724_VISIT_RESERVE_REGIST_RES = 724;</code>
     */
    public static final int M0724_VISIT_RESERVE_REGIST_RES_VALUE = 724;
    /**
     * <pre>
     * 방문 예약 이력
     * </pre>
     *
     * <code>M0725_VISIT_RESERVE_RECORD_REQ = 725;</code>
     */
    public static final int M0725_VISIT_RESERVE_RECORD_REQ_VALUE = 725;
    /**
     * <code>M0726_VISIT_RESERVE_RECORD_RES = 726;</code>
     */
    public static final int M0726_VISIT_RESERVE_RECORD_RES_VALUE = 726;
    /**
     * <pre>
     * RF 태그 리스트
     * </pre>
     *
     * <code>M0731_RGST_RF_LIST_REQ = 731;</code>
     */
    public static final int M0731_RGST_RF_LIST_REQ_VALUE = 731;
    /**
     * <code>M0732_RGST_RF_LIST_RES = 732;</code>
     */
    public static final int M0732_RGST_RF_LIST_RES_VALUE = 732;
    /**
     * <pre>
     * RF 태그 등록
     * </pre>
     *
     * <code>M0733_RGST_RF_COMMIT_REQ = 733;</code>
     */
    public static final int M0733_RGST_RF_COMMIT_REQ_VALUE = 733;
    /**
     * <code>M0734_RGST_RF_COMMIT_RES = 734;</code>
     */
    public static final int M0734_RGST_RF_COMMIT_RES_VALUE = 734;
    /**
     * <pre>
     * 공무(공용)차량 관리(조회)
     * </pre>
     *
     * <code>M0741_OFFICIAL_SEARCH_REQ = 741;</code>
     */
    public static final int M0741_OFFICIAL_SEARCH_REQ_VALUE = 741;
    /**
     * <code>M0742_OFFICIAL_SEARCH_RES = 742;</code>
     */
    public static final int M0742_OFFICIAL_SEARCH_RES_VALUE = 742;
    /**
     * <pre>
     * 공무(공용)차량 관리(설정)
     * </pre>
     *
     * <code>M0743_OFFICIAL_REGIST_REQ = 743;</code>
     */
    public static final int M0743_OFFICIAL_REGIST_REQ_VALUE = 743;
    /**
     * <code>M0744_OFFICIAL_REGIST_RES = 744;</code>
     */
    public static final int M0744_OFFICIAL_REGIST_RES_VALUE = 744;
    /**
     * <pre>
     * 주차장명 리스트업
     * </pre>
     *
     * <code>M0801_LISTUP_PARK_REQ = 801;</code>
     */
    public static final int M0801_LISTUP_PARK_REQ_VALUE = 801;
    /**
     * <code>M0802_LISTUP_PARK_RES = 802;</code>
     */
    public static final int M0802_LISTUP_PARK_RES_VALUE = 802;
    /**
     * <pre>
     * 구역명 리스트업
     * </pre>
     *
     * <code>M0803_LISTUP_ZONE_REQ = 803;</code>
     */
    public static final int M0803_LISTUP_ZONE_REQ_VALUE = 803;
    /**
     * <code>M0804_LISTUP_ZONE_RES = 804;</code>
     */
    public static final int M0804_LISTUP_ZONE_RES_VALUE = 804;
    /**
     * <pre>
     * b_장비 상태 정보
     * </pre>
     *
     * <code>M0901_B_DEVICE_INFO = 901;</code>
     */
    public static final int M0901_B_DEVICE_INFO_VALUE = 901;
    /**
     * <pre>
     * b_입차 요청
     * </pre>
     *
     * <code>M0902_B_CAR_ENTRY_REQ = 902;</code>
     */
    public static final int M0902_B_CAR_ENTRY_REQ_VALUE = 902;
    /**
     * <pre>
     * b_입차 완료
     * </pre>
     *
     * <code>M0903_B_CAR_ENTRY_COMPLATE = 903;</code>
     */
    public static final int M0903_B_CAR_ENTRY_COMPLATE_VALUE = 903;
    /**
     * <pre>
     * b_출차 요청
     * </pre>
     *
     * <code>M0905_B_CAR_EXIT_REQ = 905;</code>
     */
    public static final int M0905_B_CAR_EXIT_REQ_VALUE = 905;
    /**
     * <pre>
     * b_출차 완료
     * </pre>
     *
     * <code>M0906_B_CAR_EXIT_COMPLATE = 906;</code>
     */
    public static final int M0906_B_CAR_EXIT_COMPLATE_VALUE = 906;
    /**
     * <pre>
     * b_알림 차량
     * </pre>
     *
     * <code>M0908_B_ALARM_INFO = 908;</code>
     */
    public static final int M0908_B_ALARM_INFO_VALUE = 908;
    /**
     * <pre>
     * b_주차가능 대수
     * </pre>
     *
     * <code>M0909_B_PARKABLE_CNT = 909;</code>
     */
    public static final int M0909_B_PARKABLE_CNT_VALUE = 909;
    /**
     * <pre>
     * b_세대알림 통보
     * </pre>
     *
     * <code>M0910_B_HOMENOTI_INFO = 910;</code>
     */
    public static final int M0910_B_HOMENOTI_INFO_VALUE = 910;
    /**
     * <pre>
     * b_세대통보 요청(홈넷 중계서버에서 받아서 처리할 데이터 전송)
     * </pre>
     *
     * <code>M0911_B_HOMENOTI_REQ = 911;</code>
     */
    public static final int M0911_B_HOMENOTI_REQ_VALUE = 911;
    /**
     * <pre>
     * b_입차 데이터 보정(보조 카메라로 찍어서 차량번호 보정할 경우)
     * </pre>
     *
     * <code>M0912_B_CAR_REPLACE = 912;</code>
     */
    public static final int M0912_B_CAR_REPLACE_VALUE = 912;
    /**
     * <pre>
     * 사용자 관리(조회)
     * </pre>
     *
     * <code>M1101_USERSET_SEARCH_REQ = 1101;</code>
     */
    public static final int M1101_USERSET_SEARCH_REQ_VALUE = 1101;
    /**
     * <code>M1102_USERSET_SEARCH_RES = 1102;</code>
     */
    public static final int M1102_USERSET_SEARCH_RES_VALUE = 1102;
    /**
     * <pre>
     * 사용자 관리(설정)
     * </pre>
     *
     * <code>M1103_USERSET_REGIST_REQ = 1103;</code>
     */
    public static final int M1103_USERSET_REGIST_REQ_VALUE = 1103;
    /**
     * <code>M1104_USERSET_REGIST_RES = 1104;</code>
     */
    public static final int M1104_USERSET_REGIST_RES_VALUE = 1104;
    /**
     * <pre>
     * 주차장 관리(조회)
     * </pre>
     *
     * <code>M1105_PARKSET_SEARCH_REQ = 1105;</code>
     */
    public static final int M1105_PARKSET_SEARCH_REQ_VALUE = 1105;
    /**
     * <code>M1106_PARKSET_SEARCH_RES = 1106;</code>
     */
    public static final int M1106_PARKSET_SEARCH_RES_VALUE = 1106;
    /**
     * <pre>
     * 주차장 관리(설정)
     * </pre>
     *
     * <code>M1107_PARKSET_REGIST_REQ = 1107;</code>
     */
    public static final int M1107_PARKSET_REGIST_REQ_VALUE = 1107;
    /**
     * <code>M1108_PARKSET_REGIST_RES = 1108;</code>
     */
    public static final int M1108_PARKSET_REGIST_RES_VALUE = 1108;
    /**
     * <pre>
     * 주차 구역 관리(조회)
     * </pre>
     *
     * <code>M1109_ZONESET_SEARCH_REQ = 1109;</code>
     */
    public static final int M1109_ZONESET_SEARCH_REQ_VALUE = 1109;
    /**
     * <code>M1110_ZONESET_SEARCH_RES = 1110;</code>
     */
    public static final int M1110_ZONESET_SEARCH_RES_VALUE = 1110;
    /**
     * <pre>
     * 주차 구역 관리(설정)
     * </pre>
     *
     * <code>M1111_ZONESET_REGIST_REQ = 1111;</code>
     */
    public static final int M1111_ZONESET_REGIST_REQ_VALUE = 1111;
    /**
     * <code>M1112_ZONESET_REGIST_RES = 1112;</code>
     */
    public static final int M1112_ZONESET_REGIST_RES_VALUE = 1112;
    /**
     * <pre>
     * 장비 관리(조회)
     * </pre>
     *
     * <code>M1113_DEVICESET_SEARCH_REQ = 1113;</code>
     */
    public static final int M1113_DEVICESET_SEARCH_REQ_VALUE = 1113;
    /**
     * <code>M1114_DEVICESET_SEARCH_RES = 1114;</code>
     */
    public static final int M1114_DEVICESET_SEARCH_RES_VALUE = 1114;
    /**
     * <pre>
     * 장비 관리(설정)
     * </pre>
     *
     * <code>M1115_DEVICESET_REGIST_REQ = 1115;</code>
     */
    public static final int M1115_DEVICESET_REGIST_REQ_VALUE = 1115;
    /**
     * <code>M1116_DEVICESET_REGIST_RES = 1116;</code>
     */
    public static final int M1116_DEVICESET_REGIST_RES_VALUE = 1116;
    /**
     * <pre>
     * 코드 관리(조회)
     * </pre>
     *
     * <code>M1117_CODESET_SEARCH_REQ = 1117;</code>
     */
    public static final int M1117_CODESET_SEARCH_REQ_VALUE = 1117;
    /**
     * <code>M1118_CODESET_SEARCH_RES = 1118;</code>
     */
    public static final int M1118_CODESET_SEARCH_RES_VALUE = 1118;
    /**
     * <pre>
     * 코드 관리(설정)
     * </pre>
     *
     * <code>M1119_CODESET_REGIST_REQ = 1119;</code>
     */
    public static final int M1119_CODESET_REGIST_REQ_VALUE = 1119;
    /**
     * <code>M1120_CODESET_REGIST_RES = 1120;</code>
     */
    public static final int M1120_CODESET_REGIST_RES_VALUE = 1120;
    /**
     * <pre>
     * 패턴 번호 관리(조회)
     * </pre>
     *
     * <code>M1121_PATTERN_SEARCH_REQ = 1121;</code>
     */
    public static final int M1121_PATTERN_SEARCH_REQ_VALUE = 1121;
    /**
     * <code>M1122_PATTERN_SEARCH_RES = 1122;</code>
     */
    public static final int M1122_PATTERN_SEARCH_RES_VALUE = 1122;
    /**
     * <pre>
     * 패턴 번호 관리(설정)
     * </pre>
     *
     * <code>M1123_PATTERN_REGIST_REQ = 1123;</code>
     */
    public static final int M1123_PATTERN_REGIST_REQ_VALUE = 1123;
    /**
     * <code>M1124_PATTERN_REGIST_RES = 1124;</code>
     */
    public static final int M1124_PATTERN_REGIST_RES_VALUE = 1124;
    /**
     * <pre>
     * 전원제어기 관리(조회)
     * </pre>
     *
     * <code>M1131_POWER_CONTROLLER_LIST_REQ = 1131;</code>
     */
    public static final int M1131_POWER_CONTROLLER_LIST_REQ_VALUE = 1131;
    /**
     * <code>M1132_POWER_CONTROLLER_LIST_RES = 1132;</code>
     */
    public static final int M1132_POWER_CONTROLLER_LIST_RES_VALUE = 1132;
    /**
     * <pre>
     * 전원제어기 관리(설정)
     * </pre>
     *
     * <code>M1133_POWER_CONTROLLER_SET_REQ = 1133;</code>
     */
    public static final int M1133_POWER_CONTROLLER_SET_REQ_VALUE = 1133;
    /**
     * <code>M1134_POWER_CONTROLLER_SET_RES = 1134;</code>
     */
    public static final int M1134_POWER_CONTROLLER_SET_RES_VALUE = 1134;
    /**
     * <pre>
     * 단독 전광판 관리(조회)
     * </pre>
     *
     * <code>M1141_VMSSET_SEARCH_REQ = 1141;</code>
     */
    public static final int M1141_VMSSET_SEARCH_REQ_VALUE = 1141;
    /**
     * <code>M1142_VMSSET_SEARCH_RES = 1142;</code>
     */
    public static final int M1142_VMSSET_SEARCH_RES_VALUE = 1142;
    /**
     * <pre>
     * 단독 전광판 관리(설정)
     * </pre>
     *
     * <code>M1143_VMSSET_REGIST_REQ = 1143;</code>
     */
    public static final int M1143_VMSSET_REGIST_REQ_VALUE = 1143;
    /**
     * <code>M1144_VMSSET_REGIST_RES = 1144;</code>
     */
    public static final int M1144_VMSSET_REGIST_RES_VALUE = 1144;
    /**
     * <pre>
     * 블랙리스트 관리(조회)
     * </pre>
     *
     * <code>M1151_BLACKLISTSET_SEARCH_REQ = 1151;</code>
     */
    public static final int M1151_BLACKLISTSET_SEARCH_REQ_VALUE = 1151;
    /**
     * <code>M1152_BLACKLISTSET_SEARCH_RES = 1152;</code>
     */
    public static final int M1152_BLACKLISTSET_SEARCH_RES_VALUE = 1152;
    /**
     * <pre>
     * 블랙리스트 관리(설정)
     * </pre>
     *
     * <code>M1153_BLACKLISTSET_REGIST_REQ = 1153;</code>
     */
    public static final int M1153_BLACKLISTSET_REGIST_REQ_VALUE = 1153;
    /**
     * <code>M1154_BLACKLISTSET_REGIST_RES = 1154;</code>
     */
    public static final int M1154_BLACKLISTSET_REGIST_RES_VALUE = 1154;
    /**
     * <pre>
     * 휴일 관리(조회)
     * </pre>
     *
     * <code>M1161_HOLIDAYSET_SEARCH_REQ = 1161;</code>
     */
    public static final int M1161_HOLIDAYSET_SEARCH_REQ_VALUE = 1161;
    /**
     * <code>M1162_HOLIDAYSET_SEARCH_RES = 1162;</code>
     */
    public static final int M1162_HOLIDAYSET_SEARCH_RES_VALUE = 1162;
    /**
     * <pre>
     * 휴일 관리(설정)
     * </pre>
     *
     * <code>M1163_HOLIDAYSET_REGIST_REQ = 1163;</code>
     */
    public static final int M1163_HOLIDAYSET_REGIST_REQ_VALUE = 1163;
    /**
     * <code>M1164_HOLIDAYSET_REGIST_RES = 1164;</code>
     */
    public static final int M1164_HOLIDAYSET_REGIST_RES_VALUE = 1164;
    /**
     * <pre>
     * 유도전광판(입구만차전광판) 관리(조회)
     * </pre>
     *
     * <code>M1171_GUIDANCEVMSSET_SEARCH_REQ = 1171;</code>
     */
    public static final int M1171_GUIDANCEVMSSET_SEARCH_REQ_VALUE = 1171;
    /**
     * <code>M1172_GUIDANCEVMSSET_SEARCH_RES = 1172;</code>
     */
    public static final int M1172_GUIDANCEVMSSET_SEARCH_RES_VALUE = 1172;
    /**
     * <pre>
     * 유도전광판(입구만차전광판) 관리(설정)
     * </pre>
     *
     * <code>M1173_GUIDANCEVMSSET_REGIST_REQ = 1173;</code>
     */
    public static final int M1173_GUIDANCEVMSSET_REGIST_REQ_VALUE = 1173;
    /**
     * <code>M1174_GUIDANCEVMSSET_REGIST_RES = 1174;</code>
     */
    public static final int M1174_GUIDANCEVMSSET_REGIST_RES_VALUE = 1174;
    /**
     * <pre>
     * 스케줄러 관리(조회)
     * </pre>
     *
     * <code>M1175_SCHEDULERSET_SEARCH_REQ = 1175;</code>
     */
    public static final int M1175_SCHEDULERSET_SEARCH_REQ_VALUE = 1175;
    /**
     * <code>M1176_SCHEDULERSET_SEARCH_RES = 1176;</code>
     */
    public static final int M1176_SCHEDULERSET_SEARCH_RES_VALUE = 1176;
    /**
     * <pre>
     * 스케줄러 관리(설정)
     * </pre>
     *
     * <code>M1177_SCHEDULERSET_REGIST_REQ = 1177;</code>
     */
    public static final int M1177_SCHEDULERSET_REGIST_REQ_VALUE = 1177;
    /**
     * <code>M1178_SCHEDULERSET_REGIST_RES = 1178;</code>
     */
    public static final int M1178_SCHEDULERSET_REGIST_RES_VALUE = 1178;
    /**
     * <pre>
     * DB초기화
     * </pre>
     *
     * <code>M1181_DB_CLEAR_REQ = 1181;</code>
     */
    public static final int M1181_DB_CLEAR_REQ_VALUE = 1181;
    /**
     * <code>M1182_DB_CLEAR_RES = 1182;</code>
     */
    public static final int M1182_DB_CLEAR_RES_VALUE = 1182;
    /**
     * <pre>
     * 기간별 입차현황
     * </pre>
     *
     * <code>M1201_ENTRY_LIST_TERM_REQ = 1201;</code>
     */
    public static final int M1201_ENTRY_LIST_TERM_REQ_VALUE = 1201;
    /**
     * <code>M1202_ENTRY_LIST_TERM_RES = 1202;</code>
     */
    public static final int M1202_ENTRY_LIST_TERM_RES_VALUE = 1202;
    /**
     * <pre>
     * 정기권 현황
     * </pre>
     *
     * <code>M1203_REGULAR_LIST_REQ = 1203;</code>
     */
    public static final int M1203_REGULAR_LIST_REQ_VALUE = 1203;
    /**
     * <code>M1204_REGULAR_LIST_RES = 1204;</code>
     */
    public static final int M1204_REGULAR_LIST_RES_VALUE = 1204;
    /**
     * <pre>
     * 방문자 현황
     * </pre>
     *
     * <code>M1205_VISIT_RESERVE_LIST_REQ = 1205;</code>
     */
    public static final int M1205_VISIT_RESERVE_LIST_REQ_VALUE = 1205;
    /**
     * <code>M1206_VISIT_RESERVE_LIST_RES = 1206;</code>
     */
    public static final int M1206_VISIT_RESERVE_LIST_RES_VALUE = 1206;
    /**
     * <pre>
     * 방문차량 집계
     * </pre>
     *
     * <code>M1207_VISIT_LIST_TOTAL_REQ = 1207;</code>
     */
    public static final int M1207_VISIT_LIST_TOTAL_REQ_VALUE = 1207;
    /**
     * <code>M1208_VISIT_LIST_TOTAL_RES = 1208;</code>
     */
    public static final int M1208_VISIT_LIST_TOTAL_RES_VALUE = 1208;
    /**
     * <pre>
     * 기간별 입차 횟수
     * </pre>
     *
     * <code>M1209_ENTRY_COUNT_TERM_REQ = 1209;</code>
     */
    public static final int M1209_ENTRY_COUNT_TERM_REQ_VALUE = 1209;
    /**
     * <code>M1210_ENTRY_COUNT_TERM_RES = 1210;</code>
     */
    public static final int M1210_ENTRY_COUNT_TERM_RES_VALUE = 1210;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static message_type valueOf(int value) {
      return forNumber(value);
    }

    public static message_type forNumber(int value) {
      switch (value) {
        case 0: return M0000_DAVANS_ENUM;
        case 1: return M0001_DEVICE_INIT_REQ;
        case 2: return M0002_DEVICE_INIT_RES;
        case 3: return M0003_DEVICE_STATUS_REQ;
        case 4: return M0004_DEVICE_STATUS_RES;
        case 5: return M0005_USER_LOGIN_REQ;
        case 6: return M0006_USER_LOGIN_RES;
        case 9: return M0009_COMMON_CODE_LIST_REQ;
        case 10: return M0010_COMMON_CODE_LIST_RES;
        case 11: return M0011_DEVICE_POSITION_INFO_REQ;
        case 12: return M0012_DEVICE_POSITION_INFO_RES;
        case 51: return M0051_DEVICE_POSITION_SET_REQ;
        case 52: return M0052_DEVICE_POSITION_SET_RES;
        case 61: return M0061_CHANGE_PASSWORD_REQ;
        case 62: return M0062_CHANGE_PASSWORD_RES;
        case 101: return M0101_GATE_OPENED_REQ;
        case 102: return M0102_GATE_OPENED_RES;
        case 103: return M0103_GATE_CONTROL_USER_REQ;
        case 104: return M0104_GATE_CONTROL_USER_RES;
        case 105: return M0105_GATE_CONTROL_DEVICE_REQ;
        case 106: return M0106_GATE_CONTROL_DEVICE_RES;
        case 107: return M0107_VMS_MSG_DEVICE_REQ;
        case 108: return M0108_VMS_MSG_DEVICE_RES;
        case 111: return M0111_POWER_CONTROL_USER_REQ;
        case 112: return M0112_POWER_CONTROL_USER_RES;
        case 113: return M0113_POWER_CONTROL_DEVICE_REQ;
        case 114: return M0114_POWER_CONTROL_DEVICE_RES;
        case 121: return M0121_GATE_CONTROL_SI_REQ;
        case 122: return M0122_GATE_CONTROL_SI_RES;
        case 201: return M0201_CAR_ENTRY_REQ;
        case 202: return M0202_CAR_ENTRY_RES;
        case 205: return M0205_CAR_REPLACE_REQ;
        case 206: return M0206_CAR_REPLACE_RES;
        case 209: return M0209_CAR_ENTRY_VISIT_REQ;
        case 210: return M0210_CAR_ENTRY_VISIT_RES;
        case 211: return M0211_CAR_ENTRY_AUTOSET_REQ;
        case 212: return M0212_CAR_ENTRY_AUTOSET_RES;
        case 221: return M0221_HOMENOTI_INFO_REQ;
        case 222: return M0221_HOMENOTI_INFO_RES;
        case 231: return M0231_VISIT_RECEIPT_USER_REQ;
        case 232: return M0232_VISIT_RECEIPT_USER_RES;
        case 233: return M0233_VISIT_RECEIPT_DEVICE_REQ;
        case 234: return M0234_VISIT_RECEIPT_DEVICE_RES;
        case 235: return M0235_VISIT_HISTORY_REQ;
        case 236: return M0236_VISIT_HISTORY_RES;
        case 301: return M0301_CAR_INFO_LIST_REQ;
        case 302: return M0302_CAR_INFO_LIST_RES;
        case 303: return M0303_CAR_LIST_REQ;
        case 304: return M0304_CAR_LIST_RES;
        case 313: return M0313_PARKABLE_CNT_REQ;
        case 314: return M0314_PARKABLE_CNT_RES;
        case 321: return M0321_USABLE_REGIST_LIST_REQ;
        case 322: return M0322_USABLE_REGIST_LIST_RES;
        case 331: return M0331_CAR_UNPROCESSED_LIST_REQ;
        case 332: return M0332_CAR_UNPROCESSED_LIST_RES;
        case 601: return M0601_CAR_OUT_MANUAL_REQ;
        case 602: return M0602_CAR_OUT_MANUAL_RES;
        case 603: return M0603_CAR_EXIT_REQ;
        case 604: return M0604_CAR_EXIT_RES;
        case 701: return M0701_RGST_INFO_LIST_REQ;
        case 702: return M0702_RGST_INFO_LIST_RES;
        case 707: return M0707_RGST_REG_COMMIT_REQ;
        case 708: return M0708_RGST_REG_COMMIT_RES;
        case 711: return M0711_RGST_REG_RECORD_REQ;
        case 712: return M0712_RGST_REG_RECORD_RES;
        case 721: return M0721_VISIT_RESERVE_SEARCH_REQ;
        case 722: return M0722_VISIT_RESERVE_SEARCH_RES;
        case 723: return M0723_VISIT_RESERVE_REGIST_REQ;
        case 724: return M0724_VISIT_RESERVE_REGIST_RES;
        case 725: return M0725_VISIT_RESERVE_RECORD_REQ;
        case 726: return M0726_VISIT_RESERVE_RECORD_RES;
        case 731: return M0731_RGST_RF_LIST_REQ;
        case 732: return M0732_RGST_RF_LIST_RES;
        case 733: return M0733_RGST_RF_COMMIT_REQ;
        case 734: return M0734_RGST_RF_COMMIT_RES;
        case 741: return M0741_OFFICIAL_SEARCH_REQ;
        case 742: return M0742_OFFICIAL_SEARCH_RES;
        case 743: return M0743_OFFICIAL_REGIST_REQ;
        case 744: return M0744_OFFICIAL_REGIST_RES;
        case 801: return M0801_LISTUP_PARK_REQ;
        case 802: return M0802_LISTUP_PARK_RES;
        case 803: return M0803_LISTUP_ZONE_REQ;
        case 804: return M0804_LISTUP_ZONE_RES;
        case 901: return M0901_B_DEVICE_INFO;
        case 902: return M0902_B_CAR_ENTRY_REQ;
        case 903: return M0903_B_CAR_ENTRY_COMPLATE;
        case 905: return M0905_B_CAR_EXIT_REQ;
        case 906: return M0906_B_CAR_EXIT_COMPLATE;
        case 908: return M0908_B_ALARM_INFO;
        case 909: return M0909_B_PARKABLE_CNT;
        case 910: return M0910_B_HOMENOTI_INFO;
        case 911: return M0911_B_HOMENOTI_REQ;
        case 912: return M0912_B_CAR_REPLACE;
        case 1101: return M1101_USERSET_SEARCH_REQ;
        case 1102: return M1102_USERSET_SEARCH_RES;
        case 1103: return M1103_USERSET_REGIST_REQ;
        case 1104: return M1104_USERSET_REGIST_RES;
        case 1105: return M1105_PARKSET_SEARCH_REQ;
        case 1106: return M1106_PARKSET_SEARCH_RES;
        case 1107: return M1107_PARKSET_REGIST_REQ;
        case 1108: return M1108_PARKSET_REGIST_RES;
        case 1109: return M1109_ZONESET_SEARCH_REQ;
        case 1110: return M1110_ZONESET_SEARCH_RES;
        case 1111: return M1111_ZONESET_REGIST_REQ;
        case 1112: return M1112_ZONESET_REGIST_RES;
        case 1113: return M1113_DEVICESET_SEARCH_REQ;
        case 1114: return M1114_DEVICESET_SEARCH_RES;
        case 1115: return M1115_DEVICESET_REGIST_REQ;
        case 1116: return M1116_DEVICESET_REGIST_RES;
        case 1117: return M1117_CODESET_SEARCH_REQ;
        case 1118: return M1118_CODESET_SEARCH_RES;
        case 1119: return M1119_CODESET_REGIST_REQ;
        case 1120: return M1120_CODESET_REGIST_RES;
        case 1121: return M1121_PATTERN_SEARCH_REQ;
        case 1122: return M1122_PATTERN_SEARCH_RES;
        case 1123: return M1123_PATTERN_REGIST_REQ;
        case 1124: return M1124_PATTERN_REGIST_RES;
        case 1131: return M1131_POWER_CONTROLLER_LIST_REQ;
        case 1132: return M1132_POWER_CONTROLLER_LIST_RES;
        case 1133: return M1133_POWER_CONTROLLER_SET_REQ;
        case 1134: return M1134_POWER_CONTROLLER_SET_RES;
        case 1141: return M1141_VMSSET_SEARCH_REQ;
        case 1142: return M1142_VMSSET_SEARCH_RES;
        case 1143: return M1143_VMSSET_REGIST_REQ;
        case 1144: return M1144_VMSSET_REGIST_RES;
        case 1151: return M1151_BLACKLISTSET_SEARCH_REQ;
        case 1152: return M1152_BLACKLISTSET_SEARCH_RES;
        case 1153: return M1153_BLACKLISTSET_REGIST_REQ;
        case 1154: return M1154_BLACKLISTSET_REGIST_RES;
        case 1161: return M1161_HOLIDAYSET_SEARCH_REQ;
        case 1162: return M1162_HOLIDAYSET_SEARCH_RES;
        case 1163: return M1163_HOLIDAYSET_REGIST_REQ;
        case 1164: return M1164_HOLIDAYSET_REGIST_RES;
        case 1171: return M1171_GUIDANCEVMSSET_SEARCH_REQ;
        case 1172: return M1172_GUIDANCEVMSSET_SEARCH_RES;
        case 1173: return M1173_GUIDANCEVMSSET_REGIST_REQ;
        case 1174: return M1174_GUIDANCEVMSSET_REGIST_RES;
        case 1175: return M1175_SCHEDULERSET_SEARCH_REQ;
        case 1176: return M1176_SCHEDULERSET_SEARCH_RES;
        case 1177: return M1177_SCHEDULERSET_REGIST_REQ;
        case 1178: return M1178_SCHEDULERSET_REGIST_RES;
        case 1181: return M1181_DB_CLEAR_REQ;
        case 1182: return M1182_DB_CLEAR_RES;
        case 1201: return M1201_ENTRY_LIST_TERM_REQ;
        case 1202: return M1202_ENTRY_LIST_TERM_RES;
        case 1203: return M1203_REGULAR_LIST_REQ;
        case 1204: return M1204_REGULAR_LIST_RES;
        case 1205: return M1205_VISIT_RESERVE_LIST_REQ;
        case 1206: return M1206_VISIT_RESERVE_LIST_RES;
        case 1207: return M1207_VISIT_LIST_TOTAL_REQ;
        case 1208: return M1208_VISIT_LIST_TOTAL_RES;
        case 1209: return M1209_ENTRY_COUNT_TERM_REQ;
        case 1210: return M1210_ENTRY_COUNT_TERM_RES;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<message_type>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        message_type> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<message_type>() {
            public message_type findValueByNumber(int number) {
              return message_type.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return kr.co.daontec.dto.proto.DavansEnum.getDescriptor().getEnumTypes().get(0);
    }

    private static final message_type[] VALUES = values();

    public static message_type valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private message_type(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:davans.message_type)
  }


  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\021davans.enum.proto\022\006davans*\210&\n\014message_" +
      "type\022\025\n\021M0000_DAVANS_ENUM\020\000\022\031\n\025M0001_DEV" +
      "ICE_INIT_REQ\020\001\022\031\n\025M0002_DEVICE_INIT_RES\020" +
      "\002\022\033\n\027M0003_DEVICE_STATUS_REQ\020\003\022\033\n\027M0004_" +
      "DEVICE_STATUS_RES\020\004\022\030\n\024M0005_USER_LOGIN_" +
      "REQ\020\005\022\030\n\024M0006_USER_LOGIN_RES\020\006\022\036\n\032M0009" +
      "_COMMON_CODE_LIST_REQ\020\t\022\036\n\032M0010_COMMON_" +
      "CODE_LIST_RES\020\n\022\"\n\036M0011_DEVICE_POSITION" +
      "_INFO_REQ\020\013\022\"\n\036M0012_DEVICE_POSITION_INF" +
      "O_RES\020\014\022!\n\035M0051_DEVICE_POSITION_SET_REQ" +
      "\0203\022!\n\035M0052_DEVICE_POSITION_SET_RES\0204\022\035\n" +
      "\031M0061_CHANGE_PASSWORD_REQ\020=\022\035\n\031M0062_CH" +
      "ANGE_PASSWORD_RES\020>\022\031\n\025M0101_GATE_OPENED" +
      "_REQ\020e\022\031\n\025M0102_GATE_OPENED_RES\020f\022\037\n\033M01" +
      "03_GATE_CONTROL_USER_REQ\020g\022\037\n\033M0104_GATE" +
      "_CONTROL_USER_RES\020h\022!\n\035M0105_GATE_CONTRO" +
      "L_DEVICE_REQ\020i\022!\n\035M0106_GATE_CONTROL_DEV" +
      "ICE_RES\020j\022\034\n\030M0107_VMS_MSG_DEVICE_REQ\020k\022" +
      "\034\n\030M0108_VMS_MSG_DEVICE_RES\020l\022 \n\034M0111_P" +
      "OWER_CONTROL_USER_REQ\020o\022 \n\034M0112_POWER_C" +
      "ONTROL_USER_RES\020p\022\"\n\036M0113_POWER_CONTROL" +
      "_DEVICE_REQ\020q\022\"\n\036M0114_POWER_CONTROL_DEV" +
      "ICE_RES\020r\022\035\n\031M0121_GATE_CONTROL_SI_REQ\020y" +
      "\022\035\n\031M0122_GATE_CONTROL_SI_RES\020z\022\030\n\023M0201" +
      "_CAR_ENTRY_REQ\020\311\001\022\030\n\023M0202_CAR_ENTRY_RES" +
      "\020\312\001\022\032\n\025M0205_CAR_REPLACE_REQ\020\315\001\022\032\n\025M0206" +
      "_CAR_REPLACE_RES\020\316\001\022\036\n\031M0209_CAR_ENTRY_V" +
      "ISIT_REQ\020\321\001\022\036\n\031M0210_CAR_ENTRY_VISIT_RES" +
      "\020\322\001\022 \n\033M0211_CAR_ENTRY_AUTOSET_REQ\020\323\001\022 \n" +
      "\033M0212_CAR_ENTRY_AUTOSET_RES\020\324\001\022\034\n\027M0221" +
      "_HOMENOTI_INFO_REQ\020\335\001\022\034\n\027M0221_HOMENOTI_" +
      "INFO_RES\020\336\001\022!\n\034M0231_VISIT_RECEIPT_USER_" +
      "REQ\020\347\001\022!\n\034M0232_VISIT_RECEIPT_USER_RES\020\350" +
      "\001\022#\n\036M0233_VISIT_RECEIPT_DEVICE_REQ\020\351\001\022#" +
      "\n\036M0234_VISIT_RECEIPT_DEVICE_RES\020\352\001\022\034\n\027M" +
      "0235_VISIT_HISTORY_REQ\020\353\001\022\034\n\027M0236_VISIT" +
      "_HISTORY_RES\020\354\001\022\034\n\027M0301_CAR_INFO_LIST_R" +
      "EQ\020\255\002\022\034\n\027M0302_CAR_INFO_LIST_RES\020\256\002\022\027\n\022M" +
      "0303_CAR_LIST_REQ\020\257\002\022\027\n\022M0304_CAR_LIST_R" +
      "ES\020\260\002\022\033\n\026M0313_PARKABLE_CNT_REQ\020\271\002\022\033\n\026M0" +
      "314_PARKABLE_CNT_RES\020\272\002\022!\n\034M0321_USABLE_" +
      "REGIST_LIST_REQ\020\301\002\022!\n\034M0322_USABLE_REGIS" +
      "T_LIST_RES\020\302\002\022#\n\036M0331_CAR_UNPROCESSED_L" +
      "IST_REQ\020\313\002\022#\n\036M0332_CAR_UNPROCESSED_LIST" +
      "_RES\020\314\002\022\035\n\030M0601_CAR_OUT_MANUAL_REQ\020\331\004\022\035" +
      "\n\030M0602_CAR_OUT_MANUAL_RES\020\332\004\022\027\n\022M0603_C" +
      "AR_EXIT_REQ\020\333\004\022\027\n\022M0604_CAR_EXIT_RES\020\334\004\022" +
      "\035\n\030M0701_RGST_INFO_LIST_REQ\020\275\005\022\035\n\030M0702_" +
      "RGST_INFO_LIST_RES\020\276\005\022\036\n\031M0707_RGST_REG_" +
      "COMMIT_REQ\020\303\005\022\036\n\031M0708_RGST_REG_COMMIT_R" +
      "ES\020\304\005\022\036\n\031M0711_RGST_REG_RECORD_REQ\020\307\005\022\036\n" +
      "\031M0712_RGST_REG_RECORD_RES\020\310\005\022#\n\036M0721_V" +
      "ISIT_RESERVE_SEARCH_REQ\020\321\005\022#\n\036M0722_VISI" +
      "T_RESERVE_SEARCH_RES\020\322\005\022#\n\036M0723_VISIT_R" +
      "ESERVE_REGIST_REQ\020\323\005\022#\n\036M0724_VISIT_RESE" +
      "RVE_REGIST_RES\020\324\005\022#\n\036M0725_VISIT_RESERVE" +
      "_RECORD_REQ\020\325\005\022#\n\036M0726_VISIT_RESERVE_RE" +
      "CORD_RES\020\326\005\022\033\n\026M0731_RGST_RF_LIST_REQ\020\333\005" +
      "\022\033\n\026M0732_RGST_RF_LIST_RES\020\334\005\022\035\n\030M0733_R" +
      "GST_RF_COMMIT_REQ\020\335\005\022\035\n\030M0734_RGST_RF_CO" +
      "MMIT_RES\020\336\005\022\036\n\031M0741_OFFICIAL_SEARCH_REQ" +
      "\020\345\005\022\036\n\031M0742_OFFICIAL_SEARCH_RES\020\346\005\022\036\n\031M" +
      "0743_OFFICIAL_REGIST_REQ\020\347\005\022\036\n\031M0744_OFF" +
      "ICIAL_REGIST_RES\020\350\005\022\032\n\025M0801_LISTUP_PARK" +
      "_REQ\020\241\006\022\032\n\025M0802_LISTUP_PARK_RES\020\242\006\022\032\n\025M" +
      "0803_LISTUP_ZONE_REQ\020\243\006\022\032\n\025M0804_LISTUP_" +
      "ZONE_RES\020\244\006\022\030\n\023M0901_B_DEVICE_INFO\020\205\007\022\032\n" +
      "\025M0902_B_CAR_ENTRY_REQ\020\206\007\022\037\n\032M0903_B_CAR" +
      "_ENTRY_COMPLATE\020\207\007\022\031\n\024M0905_B_CAR_EXIT_R" +
      "EQ\020\211\007\022\036\n\031M0906_B_CAR_EXIT_COMPLATE\020\212\007\022\027\n" +
      "\022M0908_B_ALARM_INFO\020\214\007\022\031\n\024M0909_B_PARKAB" +
      "LE_CNT\020\215\007\022\032\n\025M0910_B_HOMENOTI_INFO\020\216\007\022\031\n" +
      "\024M0911_B_HOMENOTI_REQ\020\217\007\022\030\n\023M0912_B_CAR_" +
      "REPLACE\020\220\007\022\035\n\030M1101_USERSET_SEARCH_REQ\020\315" +
      "\010\022\035\n\030M1102_USERSET_SEARCH_RES\020\316\010\022\035\n\030M110" +
      "3_USERSET_REGIST_REQ\020\317\010\022\035\n\030M1104_USERSET" +
      "_REGIST_RES\020\320\010\022\035\n\030M1105_PARKSET_SEARCH_R" +
      "EQ\020\321\010\022\035\n\030M1106_PARKSET_SEARCH_RES\020\322\010\022\035\n\030" +
      "M1107_PARKSET_REGIST_REQ\020\323\010\022\035\n\030M1108_PAR" +
      "KSET_REGIST_RES\020\324\010\022\035\n\030M1109_ZONESET_SEAR" +
      "CH_REQ\020\325\010\022\035\n\030M1110_ZONESET_SEARCH_RES\020\326\010" +
      "\022\035\n\030M1111_ZONESET_REGIST_REQ\020\327\010\022\035\n\030M1112" +
      "_ZONESET_REGIST_RES\020\330\010\022\037\n\032M1113_DEVICESE" +
      "T_SEARCH_REQ\020\331\010\022\037\n\032M1114_DEVICESET_SEARC" +
      "H_RES\020\332\010\022\037\n\032M1115_DEVICESET_REGIST_REQ\020\333" +
      "\010\022\037\n\032M1116_DEVICESET_REGIST_RES\020\334\010\022\035\n\030M1" +
      "117_CODESET_SEARCH_REQ\020\335\010\022\035\n\030M1118_CODES" +
      "ET_SEARCH_RES\020\336\010\022\035\n\030M1119_CODESET_REGIST" +
      "_REQ\020\337\010\022\035\n\030M1120_CODESET_REGIST_RES\020\340\010\022\035" +
      "\n\030M1121_PATTERN_SEARCH_REQ\020\341\010\022\035\n\030M1122_P" +
      "ATTERN_SEARCH_RES\020\342\010\022\035\n\030M1123_PATTERN_RE" +
      "GIST_REQ\020\343\010\022\035\n\030M1124_PATTERN_REGIST_RES\020" +
      "\344\010\022$\n\037M1131_POWER_CONTROLLER_LIST_REQ\020\353\010" +
      "\022$\n\037M1132_POWER_CONTROLLER_LIST_RES\020\354\010\022#" +
      "\n\036M1133_POWER_CONTROLLER_SET_REQ\020\355\010\022#\n\036M" +
      "1134_POWER_CONTROLLER_SET_RES\020\356\010\022\034\n\027M114" +
      "1_VMSSET_SEARCH_REQ\020\365\010\022\034\n\027M1142_VMSSET_S" +
      "EARCH_RES\020\366\010\022\034\n\027M1143_VMSSET_REGIST_REQ\020" +
      "\367\010\022\034\n\027M1144_VMSSET_REGIST_RES\020\370\010\022\"\n\035M115" +
      "1_BLACKLISTSET_SEARCH_REQ\020\377\010\022\"\n\035M1152_BL" +
      "ACKLISTSET_SEARCH_RES\020\200\t\022\"\n\035M1153_BLACKL" +
      "ISTSET_REGIST_REQ\020\201\t\022\"\n\035M1154_BLACKLISTS" +
      "ET_REGIST_RES\020\202\t\022 \n\033M1161_HOLIDAYSET_SEA" +
      "RCH_REQ\020\211\t\022 \n\033M1162_HOLIDAYSET_SEARCH_RE" +
      "S\020\212\t\022 \n\033M1163_HOLIDAYSET_REGIST_REQ\020\213\t\022 " +
      "\n\033M1164_HOLIDAYSET_REGIST_RES\020\214\t\022$\n\037M117" +
      "1_GUIDANCEVMSSET_SEARCH_REQ\020\223\t\022$\n\037M1172_" +
      "GUIDANCEVMSSET_SEARCH_RES\020\224\t\022$\n\037M1173_GU" +
      "IDANCEVMSSET_REGIST_REQ\020\225\t\022$\n\037M1174_GUID" +
      "ANCEVMSSET_REGIST_RES\020\226\t\022\"\n\035M1175_SCHEDU" +
      "LERSET_SEARCH_REQ\020\227\t\022\"\n\035M1176_SCHEDULERS" +
      "ET_SEARCH_RES\020\230\t\022\"\n\035M1177_SCHEDULERSET_R" +
      "EGIST_REQ\020\231\t\022\"\n\035M1178_SCHEDULERSET_REGIS" +
      "T_RES\020\232\t\022\027\n\022M1181_DB_CLEAR_REQ\020\235\t\022\027\n\022M11" +
      "82_DB_CLEAR_RES\020\236\t\022\036\n\031M1201_ENTRY_LIST_T" +
      "ERM_REQ\020\261\t\022\036\n\031M1202_ENTRY_LIST_TERM_RES\020" +
      "\262\t\022\033\n\026M1203_REGULAR_LIST_REQ\020\263\t\022\033\n\026M1204" +
      "_REGULAR_LIST_RES\020\264\t\022!\n\034M1205_VISIT_RESE" +
      "RVE_LIST_REQ\020\265\t\022!\n\034M1206_VISIT_RESERVE_L" +
      "IST_RES\020\266\t\022\037\n\032M1207_VISIT_LIST_TOTAL_REQ" +
      "\020\267\t\022\037\n\032M1208_VISIT_LIST_TOTAL_RES\020\270\t\022\037\n\032" +
      "M1209_ENTRY_COUNT_TERM_REQ\020\271\t\022\037\n\032M1210_E" +
      "NTRY_COUNT_TERM_RES\020\272\tB\031\n\027kr.co.daontec." +
      "dto.protob\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
